### ISSUE TITLE
issueベースの開発　レビュー依頼

### ISSUE THREAD

**Issue by submerged-nu** [submerged-nu/oshikatsu#18]

**Comment by submerged-nu** [comment]
## 概要
webアプリ オシカツ！の機能一覧とページです

## MVPリリースまでの機能一覧
- [ ] ユーザー新規登録
- [ ] ログイン
- [ ] 新規投稿
- [ ] ランキング
- [ ] 投稿詳細
- [ ] ユーザー詳細
- [ ] ユーザー編集
- [ ] Xへの共有
- [ ] お問い合わせ
- [ ] プライバシーポリシー
- [ ] レイアウトを整える
- [ ] 検索機能
- [ ] コメント機能
- [ ] いいね

## 必要なページ
- [ ] トップページ
- [ ] 新規登録画面
- [ ] ログイン画面
- [ ] 新規投稿画面
- [ ] 新着投稿一覧
- [ ] ランキング
- [ ] ユーザー詳細
- [ ] ユーザー編集
- [ ] 投稿詳細

**Comment by submerged-nu** [comment]
申し訳ございません
貼り付けたリンクに不備がありました
修正して再度貼り直しました

**Comment by submerged-nu** [comment]
プロジェクトとリポジトリの紐付けを行いました
またプロジェクトとリポジトリがpublicになっていることを確認しました
よろしくお願いします

**Comment by submerged-nu** [comment]
## 概要
webアプリ オシカツ！の機能一覧とページです

## MVPリリースまでの機能一覧
- [ ] ユーザー新規登録
- [ ] ログイン
- [ ] 新規投稿
- [ ] ランキング
- [ ] 投稿詳細
- [ ] ユーザー詳細
- [ ] ユーザー編集
- [ ] Xへの共有
- [ ] お問い合わせ
- [ ] プライバシーポリシー
- [ ] レイアウトを整える
- [ ] 検索機能
- [ ] コメント機能
- [ ] いいね

## 必要なページ
- [ ] トップページ
- [ ] 新規登録画面
- [ ] ログイン画面
- [ ] 新規投稿画面
- [ ] 新着投稿一覧
- [ ] ランキング
- [ ] ユーザー詳細
- [ ] ユーザー編集
- [ ] 投稿詳細

見やすいように下にも貼り付けておきます

**Comment by ooooose** [comment]
いいと思います、LGTMです！
