### ISSUE TITLE
レビュー用issue

### ISSUE THREAD

**Issue by submerged-nu** [submerged-nu/oshikatsu#75]
## 各種情報
サービス名: オシカツ！
サービスURL: https://oshikatsu-8f6181ed6ae5.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ユーザー新規登録
- [ ] ログイン
- [ ] 新規投稿
- [ ] ランキング
- [ ] 投稿詳細
- [ ] ユーザー詳細
- [ ] ユーザー編集
- [ ] Xへの共有
- [ ] お問い合わせ
- [ ] プライバシーポリシー
- [ ] 検索機能
- [ ] コメント機能
- [ ] いいね

ヘッダーの新規登録をクリック→ユーザー新規登録画面へ
ヘッダーのログインをクリック→ログイン画面へ
ログイン後にヘッダーに表示される投稿するをクリック→新規投稿画面へ
サイドバーのランキングをクリック→ランキングページへ
投稿の画像をクリック→モーダルで投稿詳細
投稿詳細のユーザーアイコンをクリック→ユーザー詳細へ
ユーザー詳細ページで本人に限り表示されるボタンをクリック→ユーザー編集へ
ユーザー詳細ページで本人に限り表示されるアイコンをクリック→Xへの共有
サイドバーのお問い合わせをクリック→管理者のXアカウントへ
サイドバーのプライバシーポリシーをクリック→プライバシーポリシーへ
新着ページの上部にある検索ボタンをクリック→投稿の絞りこみ
モーダルの投稿詳細でコメントボタンをクリック→コメント可能
投稿の右下のハートをクリック→いいね

## サービスイメージがわかるようなスクリーンショット等
管理画面などはありません
代わりにroleがadminになっているユーザーはすべての投稿に対して削除ボタンが表示され、削除できます

![Image](https://github.com/submerged-nu/oshikatsu/assets/141556890/6383c019-89bc-4440-b310-976b300fbd2c)

![Image](https://github.com/submerged-nu/oshikatsu/assets/141556890/032f35a4-a8e8-442d-8668-aa12d13c6788)

**Comment by kenchasonakai** [comment]
動作確認できました！
LGTMです！

**Comment by submerged-nu** [comment]
ありがとうございました
